source 'https://rubygems.org'

ruby '2.4.0'

group :development, :test do
  gem 'capybara'
  gem 'pry'
  gem 'rake'
  gem 'rspec'
  gem 'rubocop'
  gem 'simplecov'
  gem 'simplecov-console'
  gem 'sinatra'
  gem 'shotgun'
end
